id: docker-compose-yml

info:
  name: Docker Compose Check
  author: reewardius
  severity: medium
  tags: docker,config-files,generic
  
http:
  - method: GET
    path:
      - "{{BaseURL}}/.env-docker-compose"
      - "{{BaseURL}}/adm.docker-compose.yaml"
      - "{{BaseURL}}/adm.docker-compose.yml"
      - "{{BaseURL}}/admin.docker-compose.yaml"
      - "{{BaseURL}}/admin.docker-compose.yml"
      - "{{BaseURL}}/cd.docker-compose.yaml"
      - "{{BaseURL}}/cd.docker-compose.yml"
      - "{{BaseURL}}/ci.docker-compose.yaml"
      - "{{BaseURL}}/ci.docker-compose.yml"
      - "{{BaseURL}}/cicd.docker-compose.yaml"
      - "{{BaseURL}}/cicd.docker-compose.yml"
      - "{{BaseURL}}/config/docker-compose.yaml"
      - "{{BaseURL}}/config/docker-compose.yml"
      - "{{BaseURL}}/default.docker-compose"
      - "{{BaseURL}}/default.docker-compose.yml"
      - "{{BaseURL}}/deploy.docker-compose.yaml"
      - "{{BaseURL}}/deploy.docker-compose.yml"
      - "{{BaseURL}}/dev.docker-compose.yaml"
      - "{{BaseURL}}/dev.docker-compose.yml"
      - "{{BaseURL}}/docker-compose"
      - "{{BaseURL}}/docker-compose-dev.yml"
      - "{{BaseURL}}/docker-compose-prod.yml"
      - "{{BaseURL}}/docker-compose.1.yaml"
      - "{{BaseURL}}/docker-compose.1.yml"
      - "{{BaseURL}}/docker-compose.2.yaml"
      - "{{BaseURL}}/docker-compose.2.yml"
      - "{{BaseURL}}/docker-compose.3.yaml"
      - "{{BaseURL}}/docker-compose.3.yml"
      - "{{BaseURL}}/docker-compose.4.yaml"
      - "{{BaseURL}}/docker-compose.4.yml"
      - "{{BaseURL}}/docker-compose.5.yaml"
      - "{{BaseURL}}/docker-compose.5.yml"
      - "{{BaseURL}}/docker-compose.adm.yaml"
      - "{{BaseURL}}/docker-compose.adm.yml"
      - "{{BaseURL}}/docker-compose.admin.yaml"
      - "{{BaseURL}}/docker-compose.admin.yml"
      - "{{BaseURL}}/docker-compose.backup.yaml"
      - "{{BaseURL}}/docker-compose.backup.yml"
      - "{{BaseURL}}/docker-compose.cd.yaml"
      - "{{BaseURL}}/docker-compose.cd.yml"
      - "{{BaseURL}}/docker-compose.ci.yaml"
      - "{{BaseURL}}/docker-compose.ci.yml"
      - "{{BaseURL}}/docker-compose.cicd.yaml"
      - "{{BaseURL}}/docker-compose.cicd.yml"
      - "{{BaseURL}}/docker-compose.config.yaml"
      - "{{BaseURL}}/docker-compose.config.yml"
      - "{{BaseURL}}/docker-compose.default"
      - "{{BaseURL}}/docker-compose.deploy.yaml"
      - "{{BaseURL}}/docker-compose.deploy.yml"
      - "{{BaseURL}}/docker-compose.dev.yaml"
      - "{{BaseURL}}/docker-compose.dev.yml"
      - "{{BaseURL}}/docker-compose.devel.yaml"
      - "{{BaseURL}}/docker-compose.devel.yml"
      - "{{BaseURL}}/docker-compose.development.yaml"
      - "{{BaseURL}}/docker-compose.development.yml"
      - "{{BaseURL}}/docker-compose.example"
      - "{{BaseURL}}/docker-compose.old.yaml"
      - "{{BaseURL}}/docker-compose.old.yml"
      - "{{BaseURL}}/docker-compose.orig.yaml"
      - "{{BaseURL}}/docker-compose.orig.yml"
      - "{{BaseURL}}/docker-compose.original.yaml"
      - "{{BaseURL}}/docker-compose.original.yml"
      - "{{BaseURL}}/docker-compose.pilot.yaml"
      - "{{BaseURL}}/docker-compose.pilot.yml"
      - "{{BaseURL}}/docker-compose.prod.yaml"
      - "{{BaseURL}}/docker-compose.prod.yml"
      - "{{BaseURL}}/docker-compose.production.yaml"
      - "{{BaseURL}}/docker-compose.production.yml"
      - "{{BaseURL}}/docker-compose.qa.yaml"
      - "{{BaseURL}}/docker-compose.qa.yml"
      - "{{BaseURL}}/docker-compose.sample"
      - "{{BaseURL}}/docker-compose.stage.yaml"
      - "{{BaseURL}}/docker-compose.stage.yml"
      - "{{BaseURL}}/docker-compose.template"
      - "{{BaseURL}}/docker-compose.test.yaml"
      - "{{BaseURL}}/docker-compose.test.yml"
      - "{{BaseURL}}/docker-compose.yaml"
      - "{{BaseURL}}/docker-compose.yaml.backup"
      - "{{BaseURL}}/docker-compose.yaml.bkp"
      - "{{BaseURL}}/docker-compose.yml"
      - "{{BaseURL}}/docker-compose.yml.backup"
      - "{{BaseURL}}/docker-compose.yml.bkp"
      - "{{BaseURL}}/docker-compose.yml.default"
      - "{{BaseURL}}/docker-compose.yml.example"
      - "{{BaseURL}}/docker-compose.yml.sample"
      - "{{BaseURL}}/docker-compose.yml.template"
      - "{{BaseURL}}/docker-compose1.yaml"
      - "{{BaseURL}}/docker-compose1.yml"
      - "{{BaseURL}}/docker-compose2.yaml"
      - "{{BaseURL}}/docker-compose2.yml"
      - "{{BaseURL}}/docker-compose3.yaml"
      - "{{BaseURL}}/docker-compose3.yml"
      - "{{BaseURL}}/docker-compose4.yaml"
      - "{{BaseURL}}/docker-compose4.yml"
      - "{{BaseURL}}/docker-compose5.yaml"
      - "{{BaseURL}}/docker-compose5.yml"
      - "{{BaseURL}}/docker/docker-compose.yaml"
      - "{{BaseURL}}/docker/docker-compose.yml"
      - "{{BaseURL}}/env-docker-compose"
      - "{{BaseURL}}/example.docker-compose"
      - "{{BaseURL}}/example.docker-compose.yml"
      - "{{BaseURL}}/prod.docker-compose.yaml"
      - "{{BaseURL}}/prod.docker-compose.yml"
      - "{{BaseURL}}/production.docker-compose.yaml"
      - "{{BaseURL}}/production.docker-compose.yml"
      - "{{BaseURL}}/prometheus.docker-compose.yml"
      - "{{BaseURL}}/template.docker-compose"
      - "{{BaseURL}}/template.docker-compose.yml"
      
    matchers-condition: or
    matchers:
      - type: word
        words:
          - "version:"
          - "services:"
          - "image:"
        part: body
        condition: and
        
      - type: word
        words:
          - "version"
          - "services"
          - "image"
          - "ports"
          - "volumes"
        part: body
        condition: and