id: ios-app-transport-security

info:
  name: Application Transport Security (ATS)
  author: reewardius
  severity: info
  tags: ios
  
file:
  - extensions:
      - all
      
    matchers:
      - type: word
        words:
          - "NSAppTransportSecurity"