id: go-mod-disclosure

info:
  name: Go.mod Disclosure
  author: DhiyaneshDk
  severity: low
  description: go.mod internal file is exposed.
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"go.mod"
  tags: dependency

http:
  - method: GET
    path:
      - "{{BaseURL}}/go.mod"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'module'
          - 'go'
          - 'require ('
        condition: and

      - type: status
        status:
          - 200