id: keycloak-openid-config

info:
  name: Keycloak openid-config
  author: rodnt
  severity: info
  tags: generic
  reference:
    - https://issues.jboss.org/browse/KEYCLOAK-571
  metadata:
    max-request: 2
    
http:
  - method: GET
    path:
      - "{{BaseURL}}/.well-known/openid-configuration"
      - "{{BaseURL}}/auth/realms/master/.well-known/openid-configuration"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - 'issuer'
          - 'authorization_endpoint'
          - 'token_endpoint'
          - 'userinfo_endpoint'
          - 'jwks_uri'
        condition: and
        case-insensitive: true