id: application-yaml

info:
  name: application.yaml detection
  author: Cristi vlad (@cristivlad25)
  severity: info
  description: Finds Application YAML files which often contain sensitive information.
  tags: config-files
  
http:
  - method: GET
    path:
      - "{{BaseURL}}/app.yaml"
      - "{{BaseURL}}/app.yml"
      - "{{BaseURL}}/src/app.yml"
      - "{{BaseURL}}/app/app.yml"
      - "{{BaseURL}}/app/app.yaml"
      - "{{BaseURL}}/src/app.yaml"
      - "{{BaseURL}}/application.yaml"
      - "{{BaseURL}}/application.yml"
      - "{{BaseURL}}/config/application.yml"
      - "{{BaseURL}}/config/application.yaml"
      - "{{BaseURL}}/config/app.yml"
      - "{{BaseURL}}/config/app.yaml"
      
    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        condition: or
        words:
          - "runtime:"
          - "spring:"
          - "datasource:"
          - "platform:"
          - "server:"
          - "job:"
          
      - type: status
        status:
          - 200
          
      - type: dsl
        condition: or
        dsl:
          - "!contains(tolower(body), '<html')"
          - "!contains(tolower(body), '<body')"
          - "!contains(tolower(body), '</h1>')"
          - "!contains(tolower(body), '</h2>')"
          - "!contains(tolower(body), '</h3>')"
          - "!contains(tolower(body), '<?xml')"
